exports.compositoresListPage = function(slist, d){
    // slist is an array of compositores
    // d is the date
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Composer Management</title>
        </head>
        <body>
            <div class="w3-card-4">

                <header class="w3-container w3-teal">
                    <h1>Composers List
                    <a class="w3-btn w3-round w3-grey" href="/compositores/registo">+</a>
                    </h1>
                    
                </header>
        
                <div class="w3-container">
                    <table class="w3-table-all">
                        <tr>
                            <th>Id</th>
                            <th>Name</th>
                            <th>Date of birth</th>
                            <th>Date of death</th>
                            <th>Period</th>
                        </tr>
                `
    for(let i=0; i < slist.length ; i++){
        pagHTML += `
                <tr>
                    <td>${slist[i].id}</td>
                    <td>
                        <a href="/compositores/${slist[i].id}">
                            ${slist[i].nome}
                        </a>
                    </td>
                    <td>${slist[i].dataNasc}</td>
                    <td>${slist[i].dataObito}</td>
                    <td>
                        <a href="/periodos/${slist[i].periodo}">
                        ${slist[i].periodo}
                        </a>
                    </td>
                    <td>
                        [<a href="/compositores/edit/${slist[i].id}">Edit</a>][<a href="/compositores/delete/${slist[i].id}">Delete</a>]
                    </td>
                </tr>
        `
    }

    pagHTML += `
            </table>
            </div>
                <footer class="w3-container w3-blue">
                    <h5>Generated by FG2024 in ${d}</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}


exports.compositorFormPage = function(d,ps){
    let pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Composer Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Composer Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id"/>
                        <label>Name</label>
                        <input class="w3-input w3-round" type="text" name="nome"/>
                        <label>Date of birth</label>
                        <input class="w3-input w3-round" type="date" name="dataNasc"/>
                        <label>Date of death</label>
                        <input class="w3-input w3-round" type="date" name="dataObito"/>
                        <label>Period</label>
                        <select name="periodo">
                        `
                        for (let i=0; i < ps.length; i++){
                            pagHTML += `<option value=${ps[i]}>${ps[i]}</option>`
                        }
                        pagHTML += `
                        </select>
                        <input class="w3-input w3-round"/>
                        <label>Info</label>
                        <input class="w3-input w3-round" type="text" name="bio"/>
                    </fieldset>
                    <br/>
                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Register</button>
                </form>

                <footer class="w3-container w3-purple">
                    <h5>Generated by FG2024 in ${d} - [<a href="/">Return</a>]</h5>
                </footer>
            
            </div>
    `
    return pagHTML
}

exports.compositorFormEditPage = function(b, d){
    let a = b[0]
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Composer Form</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-purple">
                    <h2>Composer Form</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Metadata</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id" readonly value="${a.id}"/>
                        <label>Name</label>
                        <input class="w3-input w3-round" type="text" name="nome" value="${a.nome}"/>
                        <label>Date of birth</label>
                        <input class="w3-input w3-round" type="date" name="dataNasc" value="${a.dataNasc}"/>
                        <label>Date of death</label>
                        <input class="w3-input w3-round" type="date" name="dataObito" value="${a.dataObito}"/>
                        <label>Period</label>
                        <input class="w3-input w3-round" type="text" name="periodo" value="${a.periodo}"/>
                        <label>Info</label>
                        <input class="w3-input w3-round" type="text" name="bio" value="${a.bio}"/>
                    </fieldset>

                    <button class="w3-btn w3-purple w3-mb-2" type="submit">Register</button>
                </form>

                <footer class="w3-container w3-purple">
                    <h5>Generated by EngWeb2024 in ${d} - [<a href="/">Return</a>]</h5>
                </footer>
            
            </div>
    `
    return pagHTML
}

// ---------------compositor's Page--------------------------------
// Change and adapt to current dataset...
exports.compositorPage = function(comp, d){
    compositor = comp[0]
    var pagHTML = `
    <html>
    <head>
        <title>${compositor.nome}</title>
        <meta charset="utf-8"/>
        <link rel="icon" href="favicon.png"/>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-teal">
                <h1>Composer ${compositor.id}</h1>
            </header>

            <div class="w3-container">
                <ul class="w3-ul w3-card-4" style="width:50%">
                    <li><b>ID: </b> ${compositor.id}</li>
                    <li><b>Name: </b> ${compositor.nome}</li>
                    <li><b>Date of birth: </b> ${compositor.dataNasc}</li>
                    <li><b>Date of death: </b> ${compositor.dataObito}</li>
                    <li><b>Period: </b> <a href="/periodos/${compositor.periodo}">${compositor.periodo}</a></li>
                    <li><b>Info: </b> ${compositor.bio}</li>
                </ul>
            </div>
            <div class="w3-container w3-margin-8">
                <ul class="w3-ul">
                </ul></div>
            <footer class="w3-container w3-teal">
                <address>Gerado por FG2024 em ${d} - [<a href="/">Voltar</a>]</address>
            </footer>
        </div>
    </body>
    </html>
    `
    return pagHTML
}

// -------------- Error Treatment ------------------------------
exports.errorPage = function(errorMessage, d){
    return `
    <p>${d}: Error: ${errorMessage}</p>
    `
}